.TH "3_IMPLIMENTATION Directory Reference" 3 "Sat Feb 19 2022" "Version 1" "voting system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3_IMPLIMENTATION Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain_votingSys\&.c\fP"
.br
.ti -1c
.RI "file \fBVoter_Info\&.c\fP"
.br
.ti -1c
.RI "file \fBVoter_Info\&.h\fP"
.br
.ti -1c
.RI "file \fBvoting_main\&.c\fP"
.br
.in -1c
