.TH "candidateId" 3 "Sat Feb 19 2022" "Version 1" "voting system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
candidateId
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Voter_Info\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBCdName\fP [5][20]"
.br
.ti -1c
.RI "char \fBCdParty\fP [5][20]"
.br
.ti -1c
.RI "char \fBCdSymbol\fP [5][20]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBVoter_Info\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char CdName[5][20]"

.PP
Definition at line \fB13\fP of file \fBVoter_Info\&.h\fP\&.
.SS "char CdParty[5][20]"

.PP
Definition at line \fB14\fP of file \fBVoter_Info\&.h\fP\&.
.SS "char CdSymbol[5][20]"

.PP
Definition at line \fB15\fP of file \fBVoter_Info\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for voting system from the source code\&.
