.TH "3_IMPLIMENTATION/main_votingSys.c" 3 "Sat Feb 19 2022" "Version 1" "voting system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3_IMPLIMENTATION/main_votingSys.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'Voter_Info\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBvoteInfo\fP (int)"
.br
.ti -1c
.RI "int \fBvoting\fP (int)"
.br
.ti -1c
.RI "void \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void main ()"

.PP
Definition at line \fB7\fP of file \fBmain_votingSys\&.c\fP\&.
.SS "char voteInfo (int N)"

.PP
Definition at line \fB4\fP of file \fBVoter_Info\&.c\fP\&.
.SS "int voting (int n)"

.PP
Definition at line \fB5\fP of file \fBvoting_main\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for voting system from the source code\&.
