.TH "md_3__i_m_p_l_i_m_e_n_t_a_t_i_o_n__i_m_p_l_i_m_e_n_t_a_t_i_o_n" 3 "Sat Feb 19 2022" "Version 1" "voting system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_3__i_m_p_l_i_m_e_n_t_a_t_i_o_n__i_m_p_l_i_m_e_n_t_a_t_i_o_n \- IMPLIMENTATION 

.IP "\(bu" 2
Following the architecture presented in src, a prototype for an Voting system has been developed\&.
.IP "  \(bu" 4
The developed prototype can be used on two os (windows and Linux) 
.PP

.PP

