.TH "3_IMPLIMENTATION/Voter_Info.h" 3 "Sat Feb 19 2022" "Version 1" "voting system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3_IMPLIMENTATION/Voter_Info.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBvoterId\fP"
.br
.ti -1c
.RI "struct \fBcandidateId\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcandidateId\fP \fBCdI\fP"
.br
.ti -1c
.RI "\fBvoterId\fP \fBVdI\fP"
.br
.ti -1c
.RI "int \fBvotes\fP [5]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBcandidateId\fP CdI"

.PP
Definition at line \fB17\fP of file \fBVoter_Info\&.h\fP\&.
.SS "\fBvoterId\fP VdI"

.PP
Definition at line \fB18\fP of file \fBVoter_Info\&.h\fP\&.
.SS "int votes[5]"

.PP
Definition at line \fB19\fP of file \fBVoter_Info\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for voting system from the source code\&.
