.TH "voterId" 3 "Sat Feb 19 2022" "Version 1" "voting system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
voterId
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Voter_Info\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBVoterName\fP [50][100]"
.br
.ti -1c
.RI "int \fBVoterID\fP [50]"
.br
.ti -1c
.RI "int \fBVoterMNo\fP [50]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBVoter_Info\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int VoterID[50]"

.PP
Definition at line \fB7\fP of file \fBVoter_Info\&.h\fP\&.
.SS "int VoterMNo[50]"

.PP
Definition at line \fB8\fP of file \fBVoter_Info\&.h\fP\&.
.SS "char VoterName[50][100]"

.PP
Definition at line \fB6\fP of file \fBVoter_Info\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for voting system from the source code\&.
